import { 
  Building2, 
  Stethoscope, 
  CreditCard, 
  UserCheck, 
  Package, 
  Users 
} from 'lucide-react'

/**
 * Revenue view configurations for the Revenue Insights Dashboard
 * Each view represents a different dimension of revenue analysis
 */
export const REVENUE_VIEWS = [
  {
    id: 'department',
    label: 'Department Revenue',
    icon: Building2,
    dataKey: 'departmentRevenue',
    queryFunction: 'getDepartmentRevenue',
    tooltip: 'Revenue breakdown by hospital departments'
  },
  {
    id: 'service',
    label: 'Service Types',
    icon: Stethoscope,
    dataKey: 'serviceTypeRevenue',
    queryFunction: 'getServiceTypeRevenue',
    tooltip: 'Revenue breakdown by service categories'
  },
  {
    id: 'payment',
    label: 'Payment Methods',
    icon: CreditCard,
    dataKey: 'paymentMethodDistribution',
    queryFunction: 'getPaymentMethodDistribution',
    tooltip: 'Revenue distribution by payment methods'
  },
  {
    id: 'doctor',
    label: 'Doctor Performance',
    icon: UserCheck,
    dataKey: 'doctorPerformance',
    queryFunction: 'getDoctorPerformance',
    tooltip: 'Revenue generated by each doctor'
  },
  {
    id: 'inventory',
    label: 'Inventory Costs',
    icon: Package,
    dataKey: 'inventoryCosts',
    queryFunction: 'getInventoryCosts',
    tooltip: 'Cost analysis of inventory items'
  },
  {
    id: 'patient',
    label: 'Patient Types',
    icon: Users,
    dataKey: 'patientTypeRevenue',
    queryFunction: 'getPatientTypeRevenue',
    tooltip: 'Revenue breakdown by patient categories'
  }
]

/**
 * Color palette for Revenue Insights Dashboard
 * Follows the design system with teal as primary color
 */
export const REVENUE_COLORS = {
  primary: '#14b8a6',      // Teal - default bar color
  success: '#10b981',      // Green - positive growth
  danger: '#ef4444',       // Red - negative growth
  warning: '#f59e0b',      // Amber - significant change
  slate: {
    900: '#0f172a',        // Primary text
    700: '#334155',        // Secondary text
    600: '#475569',        // Tertiary text
    500: '#64748b',        // Muted text
    300: '#cbd5e1',        // Disabled/placeholder
    200: '#e2e8f0',        // Borders
    100: '#f1f5f9',        // Backgrounds
  }
}

/**
 * Chart configuration constants
 * Defines dimensions, styling, and behavior for Recharts components
 */
export const CHART_CONFIG = {
  height: 350,
  margin: { top: 5, right: 80, left: 20, bottom: 5 },
  barRadius: [0, 8, 8, 0],
  gridStroke: '#e2e8f0',
  gridDasharray: '3 3',
  axisStroke: '#64748b',
  axisFontSize: 12,
  labelFontSize: 13,
  labelFontWeight: 600,
  yAxisWidth: 150,
  topItemsLimit: 10,
  legendMaxItems: 6
}

/**
 * Service type color mapping for consistent visualization
 */
export const SERVICE_TYPE_COLORS = {
  'Consultations': '#14b8a6',
  'Laboratory Tests': '#10b981',
  'Imaging': '#3b82f6',
  'Procedures': '#8b5cf6',
  'Medications': '#f59e0b',
  'Room Charges': '#ef4444',
  'Other Services': '#64748b'
}
